import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BookOpen, Building2, ChevronDown, GraduationCap, LayoutDashboard, LogOut, Menu, Newspaper, Plus, Search, ShieldCheck, Users, X } from 'lucide-react'
import { useAuth } from './context/AuthContext'
import { api } from './api/client'
import { EmptyState, ErrorState, LoadingState } from './components/States'

const navItems = [
  { key: 'overview', label: 'Overview', icon: LayoutDashboard },
  { key: 'students', label: 'Students', icon: GraduationCap },
  { key: 'classes', label: 'Classes', icon: Building2 },
  { key: 'posts', label: 'Posts', icon: Newspaper },
]

function Login() {
  const { signIn } = useAuth()
  const [form, setForm] = useState({ username: '', password: '' })
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event) {
    event.preventDefault(); setError(''); setBusy(true)
    try { await signIn(form.username, form.password) } catch (err) { setError(err.message) } finally { setBusy(false) }
  }
  return <main className="login-page"><div className="login-art"><div className="brand-mark">N</div><p className="eyebrow">NORTHSTAR SCHOOL</p><h1>Make every school day count.</h1><p className="muted light">A calmer command center for the people who make learning happen.</p><div className="art-note"><BookOpen size={18} /> One clear view of your community</div></div><form className="login-form" onSubmit={submit}><div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p className="muted">Use your school account to continue.</p></div><label>Username<input required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} placeholder="e.g. admin" /></label><label>Password<input required type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Your password" /></label>{error && <div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'} <ChevronDown size={16} className="rotate-270" /></button><small className="muted">Ask your administrator for an account if you are new here.</small></form></main>
}

function App() {
  const { user, loading, signOut } = useAuth()
  const [page, setPage] = useState('overview')
  const [mobileNav, setMobileNav] = useState(false)
  if (loading) return <LoadingState />
  if (!user) return <Login />
  return <div className="app-shell"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="sidebar-head"><div className="brand-mark small">N</div><span>Northstar</span><button className="icon-button mobile-only" onClick={() => setMobileNav(false)}><X size={18} /></button></div><div className="school-label">SCHOOL OFFICE</div><nav>{navItems.map(item => <button className={page === item.key ? 'nav-item active' : 'nav-item'} key={item.key} onClick={() => { setPage(item.key); setMobileNav(false) }}><item.icon size={18} />{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="mini-profile"><div className="avatar">{user.username[0].toUpperCase()}</div><div><strong>{user.username}</strong><span>{user.is_superuser ? 'Administrator' : 'Staff member'}</span></div></div><button className="nav-item" onClick={signOut}><LogOut size={18} />Sign out</button></div></aside><section className="main-area"><header className="topbar"><button className="icon-button mobile-only" onClick={() => setMobileNav(true)}><Menu size={20} /></button><div className="breadcrumb">School office <span>/</span> <strong>{navItems.find(item => item.key === page)?.label}</strong></div><div className="top-actions"><div className="top-avatar">{user.username[0].toUpperCase()}</div></div></header><main className="content">{page === 'overview' && <Overview setPage={setPage} />}{page === 'students' && <Students />}{page === 'classes' && <Classes />}{page === 'posts' && <Posts user={user} />}</main></section></div>
}

function useCollection(loader) { const [data, setData] = useState([]); const [status, setStatus] = useState('loading'); const [error, setError] = useState(''); const reload = () => { setStatus('loading'); loader().then(setData).then(() => setStatus('ready')).catch(err => { setError(err.message); setStatus('error') }) }; useEffect(reload, []); return { data, status, error, reload, setData } }

function Overview({ setPage }) { const students = useCollection(api.students); const classes = useCollection(api.classes); const posts = useCollection(api.posts); if ([students, classes, posts].some(item => item.status === 'loading')) return <LoadingState />; const active = students.data.filter(item => item.is_active).length; return <><div className="page-intro"><div><p className="eyebrow">MONDAY, AUGUST 24, 2026</p><h1>Good morning, admin.</h1><p className="muted">Here is what is happening across your school today.</p></div><button className="primary-button" onClick={() => setPage('students')}><Plus size={17} /> Add student</button></div><div className="metric-grid"><Metric icon={GraduationCap} label="Total students" value={students.data.length} detail={`${active} currently active`} color="coral" /><Metric icon={Building2} label="Classes" value={classes.data.length} detail="Across all sections" color="blue" /><Metric icon={Newspaper} label="Announcements" value={posts.data.length} detail="Published to your community" color="gold" /><Metric icon={ShieldCheck} label="Attendance rate" value="94%" detail="Up 3% from last month" color="green" /></div><div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">STUDENT ACTIVITY</p><h2>Enrollment overview</h2></div><button className="select-button">This year <ChevronDown size={15} /></button></div><div className="fake-chart"><div className="chart-bars">{[42, 56, 48, 68, 61, 78, 72, 88, 74, 91, 83, 96].map((height, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${height}%` }}></div><small>{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i]}</small></div>)}</div></div></section><section className="panel quick-panel"><div className="panel-heading"><div><p className="eyebrow">QUICK VIEW</p><h2>Recent updates</h2></div><button className="text-button" onClick={() => setPage('posts')}>View all</button></div>{posts.data.slice(0, 3).map(post => <div className="update" key={post.id}><div className="update-icon"><Newspaper size={16} /></div><div><strong>{post.title}</strong><span>{post.owner?.username || 'School office'} · {post.published ? 'Published' : 'Draft'}</span></div></div>)}{!posts.data.length && <EmptyState>No announcements published.</EmptyState>}</section></div></> }
function Metric({ icon: Icon, label, value, detail, color }) { return <div className="metric"><div className={`metric-icon ${color}`}><Icon size={20} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div> }

function Students() { const collection = useCollection(api.students); const classes = useCollection(api.classes); const [query, setQuery] = useState(''); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState(''); const filtered = useMemo(() => collection.data.filter(item => `${item.name} ${item.email} ${item.roll_no}`.toLowerCase().includes(query.toLowerCase())), [collection.data, query]); async function addStudent(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.createStudent({ name: form.get('name'), roll_no: Number(form.get('roll_no')), email: form.get('email'), age: Number(form.get('age')), is_active: true, class_id: Number(form.get('class_id')) }); setShowForm(false); setNotice('Student added successfully.'); collection.reload() } catch (err) { setNotice(err.message) } } return <><PageHeader eyebrow="DIRECTORY" title="Students" description="Keep your student directory accurate and up to date." action={<button className="primary-button" onClick={() => setShowForm(true)}><Plus size={17} /> Add student</button>} />{notice && <div className="notice">{notice}</div>}{showForm && <Modal title="Add a student" close={() => setShowForm(false)}><form className="modal-form" onSubmit={addStudent}><Field name="name" label="Full name" required /><Field name="roll_no" label="Roll number" type="number" required /><Field name="email" label="Email" type="email" required /><Field name="age" label="Age" type="number" required /><label>Class<select name="class_id" required><option value="">Select class</option>{classes.data.map(item => <option value={item.id} key={item.id}>{item.name} · {item.section}</option>)}</select></label><button className="primary-button">Save student</button></form></Modal>}{collection.status === 'loading' ? <LoadingState /> : collection.status === 'error' ? <ErrorState message={collection.error} /> : <section className="panel table-panel"><div className="table-tools"><div className="search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search students..." /></div><span className="muted">{filtered.length} records</span></div>{filtered.length ? <div className="table-scroll"><table><thead><tr><th>Student</th><th>Roll no.</th><th>Class</th><th>Status</th></tr></thead><tbody>{filtered.map(student => <tr key={student.id}><td><div className="person"><div className="avatar coral-avatar">{student.name[0]}</div><div><strong>{student.name}</strong><span>{student.email}</span></div></div></td><td>#{student.roll_no}</td><td>{student.current_class?.name || `Class ${student.class_id}`}<small className="cell-sub">{student.current_class?.section || '—'}</small></td><td><span className={student.is_active ? 'status active' : 'status inactive'}>{student.is_active ? 'Active' : 'Inactive'}</span></td></tr>)}</tbody></table></div> : <EmptyState>No students match your search.</EmptyState>}</section>}</> }
function Field({ label, ...props }) { return <label>{label}<input {...props} /></label> }

function Classes() { const collection = useCollection(api.classes); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState(''); async function addClass(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.createClass({ name: form.get('name'), section: form.get('section') }); setShowForm(false); setNotice('Class created successfully.'); collection.reload() } catch (err) { setNotice(err.message) } } return <><PageHeader eyebrow="ACADEMICS" title="Classes" description="Organize learning groups and see their sections at a glance." action={<button className="primary-button" onClick={() => setShowForm(true)}><Plus size={17} /> Add class</button>} />{notice && <div className="notice">{notice}</div>}{showForm && <Modal title="Create a class" close={() => setShowForm(false)}><form className="modal-form" onSubmit={addClass}><Field name="name" label="Class name" placeholder="e.g. Grade 10" required /><Field name="section" label="Section" placeholder="e.g. A" required /><button className="primary-button">Create class</button></form></Modal>}{collection.status === 'loading' ? <LoadingState /> : collection.status === 'error' ? <ErrorState message={collection.error} /> : <div className="class-grid">{collection.data.length ? collection.data.map(item => <div className="class-card" key={item.id}><div className="class-number">{String(item.id).padStart(2, '0')}</div><div><h3>{item.name}</h3><p>Section {item.section}</p></div><div className="class-arrow">→</div></div>) : <EmptyState>No classes created yet.</EmptyState>}</div>}</> }

function Posts({ user }) { const collection = useCollection(api.posts); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState(''); async function addPost(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.createPost({ title: form.get('title'), content: form.get('content'), published: true }); setShowForm(false); setNotice('Announcement published.'); collection.reload() } catch (err) { setNotice(err.message) } } async function removePost(id) { try { await api.deletePost(id); collection.reload() } catch (err) { setNotice(err.message) } } return <><PageHeader eyebrow="COMMUNICATIONS" title="Posts" description="Share timely updates with students, families, and staff." action={<button className="primary-button" onClick={() => setShowForm(true)}><Plus size={17} /> New announcement</button>} />{notice && <div className="notice">{notice}</div>}{showForm && <Modal title="New announcement" close={() => setShowForm(false)}><form className="modal-form" onSubmit={addPost}><Field name="title" label="Title" required /><label>Message<textarea name="content" rows="5" required /></label><button className="primary-button">Publish announcement</button></form></Modal>}{collection.status === 'loading' ? <LoadingState /> : collection.status === 'error' ? <ErrorState message={collection.error} /> : <div className="post-list">{collection.data.length ? collection.data.map(post => <article className="post-card" key={post.id}><div className="post-date">{post.published ? 'LIVE' : 'DRAFT'}</div><div className="post-body"><h3>{post.title}</h3><p>{post.content}</p><small>By {post.owner?.username || 'school office'}</small></div>{(post.owner_id === user.id || user.is_superuser) && <button className="text-button danger" onClick={() => removePost(post.id)}>Delete</button>}</article>) : <EmptyState>No announcements yet.</EmptyState>}</div>}</> }
function PageHeader({ eyebrow, title, description, action }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div>{action}</div> }
function Modal({ title, close, children }) { return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19} /></button></div>{children}</div></div> }
export default App
